package modelo.entidad;
// Generated 23 oct. 2021 17:42:12 by Hibernate Tools 4.3.1



/**
 * Videojuegos generated by hbm2java
 */
public class Videojuegos  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String director;
     private String estudio;
     private Integer año;

    public Videojuegos() {
    }

    public Videojuegos(String nombre, String director, String estudio, Integer año) {
       this.nombre = nombre;
       this.director = director;
       this.estudio = estudio;
       this.año = año;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDirector() {
        return this.director;
    }
    
    public void setDirector(String director) {
        this.director = director;
    }
    public String getEstudio() {
        return this.estudio;
    }
    
    public void setEstudio(String estudio) {
        this.estudio = estudio;
    }
    public Integer getAño() {
        return this.año;
    }
    
    public void setAño(Integer año) {
        this.año = año;
    }




}


